name: Accessible Spinbutton
author: mashalla
category: Widgets
tags: [input, spinbutton, button]
#docs: http://www.accessiblemootoolsdemo.iao.fraunhofer.de/Mootools_Widgets/index.html
demo: http://www.accessiblemootoolsdemo.iao.fraunhofer.de/Mootools_Widgets/index.html
current: 1.1

sources:
  - "Source/spinbutton.js"
  - "Source/demo.js"